server {
    listen 80;

    location = / {
        return 301 /identity_journal/;
    }

    location /identity_journal/ {
        alias /usr/share/nginx/html/identity_journal/;
        index index.html;
        try_files $uri $uri/ /identity_journal/index.html;
    }

    error_page 404 /identity_journal/index.html;
}
